<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="edu.sjsu.cs157a.forum.model.User, edu.sjsu.cs157a.forum.dao.UserDAO" %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <link rel="stylesheet" href="../css/styles.css">
</head>
<body>
    <h1>Create Account</h1>
    
    <%
    String error = null;
    String success = null;
    
    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String username = request.getParameter("username");
        String password = request.getParameter("password");
        String confirmPassword = request.getParameter("confirmPassword");
        String email = request.getParameter("email");
        
        if (username == null || username.isEmpty() ||
            password == null || password.isEmpty() ||
            email == null || email.isEmpty()) {
            error = "All fields are required";
        } else if (!password.equals(confirmPassword)) {
            error = "Passwords do not match";
        } else {
            try {
                User newUser = new User(
                    null,  // userID will be generated by DB
                    username,
                    password,
                    email,
                    null   // registerDate will be set by DB
                );
                
                UserDAO userDAO = new UserDAO();
                User createdUser = userDAO.createUser(newUser);
                
                success = "Account created successfully!";
            } catch (Exception e) {
                error = "Registration failed: " + e.getMessage();
            }
        }
    }
    %>
    
    <% if (error != null) { %>
        <div class="error"><%= error %></div>
    <% } %>
    
    <% if (success != null) { %>
        <div class="success"><%= success %></div>
    <% } else { %>
        <form method="post">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            
            <div class="form-group">
                <label for="confirmPassword">Confirm Password:</label>
                <input type="password" id="confirmPassword" name="confirmPassword" required>
            </div>
            
            <button type="submit">Sign Up</button>
        </form>
    <% } %>
    
    <p>Already have an account? <a href="login.jsp">Login here</a></p>
</body>
</html>