<%--
  signup.jsp - User registration page
  Handles new account creation with validation
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%-- Import required models and DAOs --%>
<%@ page import="edu.sjsu.cs157a.forum.model.User, edu.sjsu.cs157a.forum.dao.UserDAO" %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign Up</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.0/dist/flatly/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
</head>
<body class="bg-light">
    <!-- Include navigation -->
    <jsp:include page="../common/navigation.jsp">
        <jsp:param name="currentPage" value="signup" />
    </jsp:include>
    
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-header bg-primary text-white">
                        <h3 class="mb-0">Create Account</h3>
                    </div>
                    <div class="card-body p-4">
    
                        <%-- Registration processing logic --%>
                        <%
                        String error = null;
                        String success = null;
                        
                        // Check if form was submitted via POST
                        if ("POST".equalsIgnoreCase(request.getMethod())) {
                            // Get form parameters
                            String username = request.getParameter("username");
                            String password = request.getParameter("password");
                            String confirmPassword = request.getParameter("confirmPassword");
                            String email = request.getParameter("email");
                            
                            // Validate required fields
                            if (username == null || username.isEmpty() ||
                                password == null || password.isEmpty() ||
                                email == null || email.isEmpty()) {
                                error = "All fields are required";
                            } else if (!password.equals(confirmPassword)) {
                                error = "Passwords do not match";
                            } else {
                                try {
                                    // Create new user object (DB will set ID and registerDate)
                                    User newUser = new User(
                                        null,  // userID will be generated by DB
                                        username,
                                        password,
                                        email,
                                        null   // registerDate will be set by DB
                                    );
                                    
                                    // Save user to database
                                    UserDAO userDAO = new UserDAO();
                                    User createdUser = userDAO.createUser(newUser);
                                    
                                    success = "Account created successfully!";
                                } catch (Exception e) {
                                    error = "Registration failed: " + e.getMessage();
                                }
                            }
                        }
                        %>
                        
                        <% if (error != null) { %>
                            <div class="alert alert-danger" role="alert">
                                <i class="bi bi-exclamation-triangle-fill me-2"></i>
                                <%= error %>
                            </div>
                        <% } %>
                        
                        <% if (success != null) { %>
                            <div class="alert alert-success" role="alert">
                                <i class="bi bi-check-circle-fill me-2"></i>
                                <%= success %>
                            </div>
                        <% } else { %>
                            <%-- Registration form --%>
                            <form method="post">
                                <div class="mb-3">
                                    <label for="username" class="form-label">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="bi bi-person-fill"></i></span>
                                        <input type="text" class="form-control" id="username" name="username" required>
                                    </div>
                                </div>
                                
                                <div class="mb-3">
                                    <label for="email" class="form-label">Email</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="bi bi-envelope-fill"></i></span>
                                        <input type="email" class="form-control" id="email" name="email" required>
                                    </div>
                                </div>
                                
                                <div class="mb-3">
                                    <label for="password" class="form-label">Password</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                                        <input type="password" class="form-control" id="password" name="password" required>
                                    </div>
                                </div>
                                
                                <div class="mb-3">
                                    <label for="confirmPassword" class="form-label">Confirm Password</label>
                                    <div class="input-group">
                                        <span class="input-group-text"><i class="bi bi-key"></i></span>
                                        <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" required>
                                    </div>
                                </div>
                                
                                <div class="d-grid gap-2">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="bi bi-person-plus-fill me-2"></i>Sign Up
                                    </button>
                                </div>
                            </form>
                        <% } %>
                        
                        <div class="mt-3 text-center">
                            <p>Already have an account? <a href="login.jsp" class="text-decoration-none">Login here</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Bootstrap JS Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
